# Generated by Django 4.1 on 2022-08-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_profile_fb_url_profile_github_url_profile_insta_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='insta_url',
            new_name='instagram_url',
        ),
    ]
